#!/usr/bin/env python

import os
import sys
import subprocess as sp

dir = sys.argv[1]

dircat = os.path.join

def attrs2str(attrs):
    res = ""
    for (k, v) in attrs.items():
        res += k + ("=\"%s\"" % v) + " "
    return res

def xml_str(t, s, **attrs):
    return "<" + t +  " " + attrs2str(attrs) + ">" + s + "</" + t + ">"

def table(s):
    return xml_str("table", s)

def html(s):
    return xml_str("html", s)

def body(s):
    return xml_str("body", s)

def print_html_table_row(r):
    res = "<tr>"
    for item in r:
        res += "<td>" + item + "</td>"
    res += "</tr>"
    return res

img_rows = []
for f in os.listdir(dircat(dir, "enumeration")):
    if f.endswith(".png"):
        img_rows.append([xml_str("img", "", src = dircat(dir, "enumeration", f)), f])

dest = dircat(dir, "enumeration.html")
fh = open(dest, "w")
print >>fh, html(body(table(reduce(lambda x, y: x + "\n" + y, map(print_html_table_row, img_rows)))))
fh.close()

