#!/usr/bin/env python

import sys
import subprocess as sp
import os

model_type = [sys.argv[1]]
fan_out = [10]
n_iter = [1000]
like_weight = [1.0]
prior_weight = [1.1]
dirichlet_alpha = [0.8]
model_scale = [1]

n_trials = 10

def pr(x):
    print x

run = lambda c: pr(c) ##sp.call(c, shell = True)

cmd = lambda mt, fo, ni, lw, pw, da, ms, trial_num: """ikarus --script %s %s %s %s %s %s %s %s %s""" % (os.path.join(
    os.getenv("GI_BASE_DIR"), "bpm", "examples", "grammar-induction", "stats", "gi-proc-model.ss"), mt,
    fo, ni,
    lw, pw, da,
    ms,
    trial_num)

for n in range(n_trials):
    for mt in model_type:
        for fo in fan_out:
            for ni in n_iter:
                for lw in like_weight:
                    for pw in prior_weight:
                        for da in dirichlet_alpha:
                            for ms in model_scale:
                                run(cmd(mt, fo, ni, lw, pw, da, ms, n))


