#!/usr/bin/env python

import sys
import os
import subprocess as sp

fn = sys.argv[1]

scriptFile=os.path.join(os.getenv("GI_BASE_DIR"),"bpm","examples","grammar-induction","stats","grammar-to-church.ss")
sp.call("vicare --script %s %s" % (scriptFile, fn), shell = True)




