#!/usr/bin/env python

import subprocess
import sys
import os
import glob
import shutil

grammarDir = sys.argv[1]
grammarFile = glob.glob(os.path.join(grammarDir,"*.grammar.ss"))[0]

scriptFile=os.path.join(os.getenv("GI_BASE_DIR"),"bpm","examples","grammar-induction","stats","stochastic-count-models.ss")

subprocess.call(["vicare","--script",scriptFile, grammarFile])
